exports.internalServerErr = {type: "internalServerError", discription: "Internal server error"};
exports.requestEntityTooLarge = {type: "requestEntityTooLarge", discription: "Request entity too large"};
exports.usernameNotProvided = {type: "illegalArgument", discription: "Username must provided"};
exports.userIdNotProvided = {type: "illegalArgument", discription: "User ID must provided"};
exports.passwordNotProvided = {type: "illegalArgument", discription: "Password must provided"};
exports.userNotExists = {type: "ResourceNotFound", discription: "User not exists"};
exports.usernameAlreadyExists = {type: "duplicateEntry", discription: "Username already exists"};
exports.methodNotAllowed = {type: "methodNotAllowed", discription: "Request method not allowed"};
exports.unauthorized = {type: "unauthorized", discription: "Request unauthorized"};
